### ISSUE TITLE
Need help with YouTube Live Ingest using HLS

### ISSUE THREAD

**Issue by onos9** [Vanilagy/webm-muxer#18]
Hi there,

I'm currently working on a project that involves live streaming to YouTube using the HLS protocol. I came across your webm-muxer library and was impressed with its performance and simplicity.

However, I'm having trouble figuring out how to use it with YouTube's Live Ingest feature. I was wondering if you could provide some guidance or examples on how to do this.

Any help would be greatly appreciated!

Thank you.

Best regards.

**Comment by Vanilagy** [comment]
Ahh, I sadly don't know much about this area. Given YouTube's [docs](https://developers.google.com/youtube/v3/live/guides/ingestion-protocol-comparison), it seems like you'll need to send the data using DASH (which supports VP9), a protocol that runs over HTTP. Not quite sure what goes into that format, but I recall [this PR](https://github.com/Vanilagy/webm-muxer/pull/15#issuecomment-1500387902) mentioning live-streaming + DASH. Also no idea if you can also send WebM stuff over HLS.

Not sure if this library alone is enough for live-streaming, seems like in that PR they also used ffmpeg. I personally don't think requiring ffmpeg for anything client-side is a good idea, 'cause it's big and bulky. But yeah, I'm afraid I can't help you very much here, but continue reading into the topic and I'm sure you'll get somewhere!
