### ISSUE TITLE
Support transparency / alpha by encoding stream

### ISSUE THREAD

**Issue by akre54** [Vanilagy/webm-muxer#19]
Hi there - I'm trying to use this library to encode a VideoFrame sequence with alpha to the container (ref #9). I see that it should be possible to write an alpha channel to VP8 [because WebMWriter does it](https://github.com/thenickdude/webm-writer-js/blob/v0.3.0/src/WebMWriter.js#L562-L612), using `BlockAdditions` / `BlockAdditional`. Would it be feasible to add to this library?

Thanks for the great work!

**Comment by Vanilagy** [comment]
This library already has alpha support! Look at the muxer config definition. The problem is that VideoEncoder, at least in Chromium, doesn't support alpha video encoding. Or was that not what you were asking?

**Comment by akre54** [comment]
I guess I'm not familiar enough with what parts live where, but yes that does seem to be what I'm asking. It looks like WebMWriter doesn't use VideoEncoder but is able to get alpha channel output. Is there a hackaround for this, or would it be possible to shim the webcodecs api? (say, with an [emscripten port of vp9](https://github.com/GoogleChromeLabs/webm-wasm)) or is this a pipe dream? Thanks for your help here

**Comment by akre54** [comment]
Could I, say, pass a Uint8Array to `muxer.addVideoChunk`, or is VideoEncoder doing something very complicated here?

**Comment by Vanilagy** [comment]
I see! Yes, if you encode the frames yourself, you could use a WASM port of VP9 to encode with an alpha channel. This library supports the .addVideoChunkRaw method for this usecase! You simply pass it a Uint8Array and some metadata.

**Comment by akre54** [comment]
Oh amazing. Let me give that a shot

**Comment by akre54** [comment]
Nope! I ended up using WebM Writer directly, but hoping they'll add alpha support to the codecs soon.

Thanks for your help
