### ISSUE TITLE
webmmuxer throws Matroska cluster too big error even with 10 seconds keyframe interval.

### ISSUE THREAD

**Issue by RavikumarTulugu** [Vanilagy/webm-muxer#30]
I have a media pipeline in which the encoder stage feeds the recording stage, the recording stage uses mp4/webmmuxer to write local media file.  I was using mp4muxer and every thing works fine. But , when i switch to webmmuxer i get this below error and the recorder refuses to write the file. I am inserting keyframes every 10 milliseconds. I wonder whether some thing wrong with my usage. Are there any extra options we need to pass compared to mp4 muxer ? 

`Current Matroska cluster exceeded its maximum allowed length of 32768 milliseconds. In order to produce a correct WebM file, you must pass in a video key frame at least every 32768 milliseconds.`

please advise. 
Thanks

**Comment by Vanilagy** [comment]
Are you inserting keyframes in 10-second or 10-millisecond intervals? (your title and body conflict)
There is this section in the README:
![CleanShot 2023-11-23 at 10 10 25](https://github.com/Vanilagy/webm-muxer/assets/1696106/e6a3b97c-56ae-423c-b0b7-a86fd9fddbab)

Are you doing what it says?

**Comment by RavikumarTulugu** [comment]
sorry for the typo , it is 10 seconds and not 10 milliseconds. It is easily reproducible.

**Comment by Vanilagy** [comment]
Can you show me the code you use for muxing?

**Comment by RavikumarTulugu** [comment]
hi, the product i am working is a commercial closed source product. i will keep 32 seconds and see whether it helps. will update.

**Comment by Vanilagy** [comment]
That's fine, you can try to send only the parts that show how you use the muxer - not like that would be leaking any company secrets here :) It seems likely you're not passing `{ keyFrame: true }` to the encoder every once in a while.

**Comment by RavikumarTulugu** [comment]
I am closing it for now , as i am busy with other things.
