### ISSUE TITLE
comparison

### ISSUE THREAD

**Issue by weepy** [Vanilagy/webm-muxer#37]
can you explain why this is better or different from "recordrtc" https://github.com/muaz-khan/RecordRTC ?

**Comment by Vanilagy** [comment]
Never heard of that library, but it seems to be a library for recording MediaStreams. You don't need to go to a library for that, you can simply use [MediaRecorder](https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder). `webm-muxer` is a bit lower level, as you're not limited to recording real-time streams but can procedurally create a video offline (offline = not real time). `webm-muxer` also makes use of the (low-level) WebCodecs API, which `MediaRecorder` and the library you linked do not.

I originally built this library for a replay rendering system in [my web game](https://marbleblast.vaniverse.io/), exactly _because_ `MediaRecorder` or any type of real-time stream recording thing did not suffice and was not what I needed. The replay renderer works offline, meaning it can render the replay at any resolution or framerate desireable, and it takes as long as it needs to for that. You can render at 8K 240FPS and you'll get a perfectly smooth video out.

If all you want to do is record some real-time media, like a microphone or a screen, `MediaRecorder` should suffice for that - no need to use any library for that.

Does this answer your question somewhat?

**Comment by weepy** [comment]
Heya thanks that makes sense. Thanks for the detailed response.

I'm actually rendering some pixi.js graphics and fragment shaders in a
webgl canvas and rendering audio via the webaudio api. I want to record
these off as little music/videos, but I do want to ensure there's no
glitching - I was finding that recording the stream created a webm that
popped a bit in safari.
I'll have to experiment some more as I'm not sure what the best approach is
^_^ .

**Comment by weepy** [comment]
Amazing!  I will dig deeper. I am currently capturing the PCM output from
the graph live - so hoping i can mux it all at the end.

**Comment by Vanilagy** [comment]
Good luck!
