### ISSUE TITLE
The correction of the mp4 muxer on files encoded with vp9, I think the same could also happen to webp

### ISSUE THREAD

**Issue by tiuvi** [Vanilagy/webm-muxer#39]
Este es el mensaje de error
![image](https://github.com/Vanilagy/webm-muxer/assets/69035383/67c2c8b0-39e2-470e-bce7-c12c386a98d2)

You can see the demo at
https://tiuvi.com/videoEditorWebCodecs
If the demo is inoperative try it later, it is hosted on my own PC

The file was an mp4 file processed by webcodecs with vp9 codec and opus audio and packaged with this library in a webm container
That webm file is the one that I am now trying to transform back into webm to see that the same file can be processed several times but it gives an error.

**Comment by Vanilagy** [comment]
Lo siento, no entiendo del todo. ¿Estás insinuando que hay un error con los archivos WebM que produce mi muxer? ¿O el error está en otra parte?

**Comment by tiuvi** [comment]
Pues he producido un archivo webm con tu muxer y despues he tratado de hacer demuxer otra vez y daba este error.
es posible que este en tu biblioteca o en la biblioteca de demuxer no podria confirmar la verdad.
https://github.com/jscodec/jswebm
![image](https://github.com/Vanilagy/webm-muxer/assets/69035383/228eaa47-103f-4778-b478-1dcfdea911ae)
Yes it is true that I had to change this line because it threw an error and it did not work
Next week I will investigate more to see where the problem could be if you want.

![image](https://github.com/Vanilagy/webm-muxer/assets/69035383/cfe95aff-b60a-46e1-9b9a-f5e7faa5fd69)

In the muxer mp4 library it also produced unsigned -4 files when using vp9, maybe the error could also be here.

**Comment by tiuvi** [comment]
![image](https://github.com/Vanilagy/webm-muxer/assets/69035383/3ba53834-d42e-4935-a03e-acf68bd2ec41)

I provide more data if you do an ebml analysis with https://github.com/node-ebml/node-ebml you can see which track is undefined, I don't know that could be a problem.

**Comment by Vanilagy** [comment]
It could be there's an error in your application code where you write the WebM file - I doubt that the files are malformed, with invalid file size and all that. If this issue is still relevant, feel free to reopen it!
