### ISSUE TITLE
Recording canvas on WebGL - all is black

### ISSUE THREAD

**Issue by Fujicsso** [Vanilagy/webm-muxer#40]
Hey! I implemented this like you have it in the demo folder, but to record a canvas that is displaying 3D stuff with WebGL. But the resulting video, while having the correct length, is plain black. Any clue what might be causing that?

**Comment by Fujicsso** [comment]
Theres nothing specific going on with the code persay, its just a model in a canvas rotating for now. Are there any specific settings needed in the webgl renderer for example? The issue, I would guess, is that whenever we go about taking the image, the canvas has already been reset.

**Comment by Vanilagy** [comment]
It should work, so there's something wrong in your code. Perhaps try disabling alpha, or setting desynchronized to false, if that's true? But yes, definitely an error in the code as I know this works from my game.

I'll close this issue as it's not related to a bug in my library.
