### ISSUE TITLE
How can I process a WAV file instead of a stream?

### ISSUE THREAD

**Issue by toshusai** [Vanilagy/webm-muxer#44]
Thank you for the great library.
I want to create a WebM file by combining a non-streaming WAV file with consecutive frames from a canvas.
I suspect that I should use addAudioChunkRaw, but how should I determine the chunk size and timestamp to pass to it? I think these might be related to the WAV file's header, but is there a general example?
If you know, I would appreciate it if you could share it.

Here is an image of the code I have in mind:

```ts
fetch("./output.wav").then(async (res) => {
  const buffer = await res.arrayBuffer();
  const data = new Uint8Array(buffer, 44, buffer.byteLength - 44);
  const chunkSize = "?";
  for (let i = 0; i < data.length; i += chunkSize) {
    const block = data.slice(i, i + chunkSize);
    const timestamp = "?";
    muxer.addAudioChunkRaw(block, "key", timestamp);
  }
});
```

**Comment by Vanilagy** [comment]
The audio chunks added to the muxer are expected to be short (something like 1024 samples per chunk) and frequent - this makes it easy for players to perform random access. So, if you wanted to add the WAV file directly, you'd pick some chunk size yourself (like 1024), then chunk the audio file and then add each chunk to the muxer. Additionally, you'll need to parse certain metadata like bit depth, channel count and sample rate from the WAV header. You can look into the makeup of the WAV header here: https://docs.fileformat.com/audio/wav/

All of this assumes your intention is to add the WAV data directly to the muxer. This would imply that you use the appropriate codec string as well, such as `A_PCM/INT/LIT`. If you are fine with lossless audio instead, you can pipe the wave file through an `AudioEncoder` which gives you the chunks directly. For this, you'd load the WAV file using an AudioContext into an AudioBuffer, then construct an AudioData from that buffer, and then pipe that AudioData into the encoder. The encoder could use any supported codec, such as Opus. AudioDecoder also supports raw codecs such as `pcm-s16` by the spec, but they aren't actually supported in any browser right now (but will be soon).

**Comment by toshusai** [comment]
Thank you for your response. I tried using AudioContext and AudioEncoder, and it worked to some extent. However, the output audio data seems to have some noise, resulting in lower quality.

Here is the repository and source code where I conducted the tests. 
https://github.com/toshusai/webm-muxer-test/blob/main/src/main.ts#L112

I apologize for not being very familiar with the internal workings of media files, but if there's anything I did wrong, I would appreciate it if you could let me know.

**Comment by Vanilagy** [comment]
The section where you create the AudioData is incorrect. The format used by AudioBuffers is f32, so you'll need to use that instead of s16. Additionally, you're only using the data from one channel even though your audio might have multiple channels. There are two ways to pack multiple channels into one array buffer: interleaved or planar. Interleaved is the default, where it's a sample from channel 1, then from channel 2, then from channel 1 again and so on. The simpler option is planar (f32-planar is the format), where it's all data from channel 1 followed by all data from channel 2. So you'll wanna create a Float32Array of length sampleCount*numOfChannels, and then copy all channel data into there in a planar fashion. Can you try that out?

Something like this:
```ts
fetch("./output.wav").then(async (res) => {
    const audioEncoder = new AudioEncoder({
        output: (chunk, meta) => {
            muxer.addAudioChunk(chunk, meta);
        },
        error: console.error,
    });

    const buffer = await res.arrayBuffer();
    const audioContext = new AudioContext();
    const audioBuffer = await audioContext.decodeAudioData(buffer);

    const numberOfChannels = audioBuffer.numberOfChannels;
    const length = audioBuffer.length;
    const sampleRate = audioBuffer.sampleRate;

    audioEncoder.configure({
        codec: "opus",
        sampleRate: sampleRate,
        numberOfChannels: numberOfChannels,
        bitrate: sampleRate * numberOfChannels * 16,
    });

    // Create a Float32Array to hold the planar data
    const planarData = new Float32Array(length * numberOfChannels);

    // Copy channel data into planarData in a planar fashion
    for (let channel = 0; channel < numberOfChannels; channel++) {
        const channelData = audioBuffer.getChannelData(channel);
        planarData.set(channelData, channel * length);
    }

    const audioData = new AudioData({
        format: "f32-planar",
        sampleRate: sampleRate,
        numberOfFrames: length,
        numberOfChannels: numberOfChannels,
        timestamp: 0,
        data: planarData,
    });

    audioEncoder.encode(audioData);
});
```

**Comment by toshusai** [comment]
Thank you for your confirmation. It seems to have worked well after making the corrections as you pointed out! I sincerely appreciate your response to my question and the detailed code examples.
