### ISSUE TITLE
demo & demo-streaming  is not working

### ISSUE THREAD

**Issue by hiroMTB** [Vanilagy/webm-muxer#46]
https://vanilagy.github.io/webm-muxer/demo-streaming/

tested on macOS Chrome

**Comment by Vanilagy** [comment]
Can't argue with that

Good catch!

**Comment by hiroMTB** [comment]
wow, super fast!

**Comment by hiroMTB** [comment]
This is not fixed yet at least on latest Chrome + macOS environment.
Error is "Input audio buffer is incompatible with codec parameters"

**Comment by Vanilagy** [comment]
@hiroMTB Hey, can you try out the [demo](https://vanilagy.github.io/webm-muxer/demo/) again? I made a little adjustment to the code, but I need to verify this fixes it for you.

**Comment by hiroMTB** [comment]
demo started working!
streaming-demo might need the same modification.
I was using 1ch 96k audio sampling rate for the audio input, that must give me this error.

**Comment by Vanilagy** [comment]
@hiroMTB Yes, I'm gonna modify the other demos then, I just wanted to verify the fix.
