### ISSUE TITLE
read webm 

### ISSUE THREAD

**Issue by juntaosun** [Vanilagy/webm-muxer#5]
Can I increase the read frame data in webm format to match WebCodecs to draw and play canvas?

VideoDecoder;

`  
（........ webm track, frame, chunk？ ........ )

    videoDecoder.decode(chunk);
`

**Comment by Vanilagy** [comment]
I'm not quite sure what you mean. If you're trying to read or parse WebM, this library won't help you. It's meant for writing WebM files.
