### ISSUE TITLE
Support mobile chrome

### ISSUE THREAD

**Issue by gut4** [Vanilagy/webm-muxer#6]
[Demo](https://vanilagy.github.io/webm-muxer/demo/) is failed in chrome mobile(110 & 111) with errors:
```
DOMException: Input audio buffer is incompatible with codec parameters
Uncaught (in promise) DOMException: Failed to execute 'encode' on 'AudioEncoder': Cannot call 'encode' on a closed codec
```
Looks like it should work
https://caniuse.com/webcodecs

**Comment by Vanilagy** [comment]
Seems like your user agent doesn't support Opus. You're free to use any other codec in your own project, it's just the demo that's broken for you.
