### ISSUE TITLE
Support safari

### ISSUE THREAD

**Issue by gut4** [Vanilagy/webm-muxer#7]
Safari is add webcodecs support(video only for now) in latest dev releases (https://caniuse.com/webcodecs)

Сurrently [demo](https://vanilagy.github.io/webm-muxer/demo/) is failing with error:
```
[Error] Unhandled Promise Rejection: ReferenceError: Can't find variable: AudioEncoder
```

**Comment by Vanilagy** [comment]
This library makes no assumptions about the WebCodecs API existing or not. You can use it with your own encoders using the `raw` methods. It's just the demo that assumes that the user is using a browser that supports them.

**Comment by Vanilagy** [comment]
For clarity, I added some additional feature checks to the demo script to address this issue.
