### ISSUE TITLE
Encode alpha video to WebM ?

### ISSUE THREAD

**Issue by juntaosun** [Vanilagy/webm-muxer#9]
Chrome 31 now supports video alpha transparency in WebM.
"webm-muxer" How to Encoder alpha videos ? 

VideoEncoderConfig：
alpha: 'keep',   // keep alpha channel

It doesn't work

**Comment by Vanilagy** [comment]
👀 works in the next mediabunny version 👀

**Comment by yisibl** [comment]
See also
- https://github.com/Vanilagy/mediabunny/issues/55#issuecomment-3330349415
- https://github.com/Vanilagy/mediabunny/releases/tag/v1.20.0
